### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by t10801606** [t10801606/furima-31126#11]
ご確認お願いします。

#URL
https://furima-31126.herokuapp.com/

#Basic認証のIDとパスワード
ユーザー名：admin
パスワード：2222

#出品者用のメールアドレスとパスワード
furima@suzuki.com
suzuki1234

#購入者用のメールアドレスとパスワード
furima@takada.com
takada1234

#カード情報
カード番号：4242424242424242
有効期限：1月23年
セキュリティコード：123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
### [修正箇所]
**①いただいたカード情報を入力しても、購入が完了できない**
👇入力した情報はこちらです👇※ハイフン等の指定があれば教えて下さい。
![furima-31126 herokuapp com_items_21_buyers](https://user-images.githubusercontent.com/49669977/97662902-93742100-1abb-11eb-8d2d-34a4ce0ac18c.png)


上記のため、以下の項目については次回以降確認いたします。
```
・購入した商品は、再度購入できない状態になっている
・購入が完了したら、トップページまたは購入完了ページに遷移する
・URLを直接入力して購入済み商品の購入ページへ遷移しようとすると、トップページに遷移する
・クレジットカード情報は必須であり、正しいクレジットカードの情報で無いときは決済できない
・エラーハンドリングができていること（適切では無い値が入力された場合、情報は保存されず、エラーメッセージを出力させる）
```

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by t10801606** [comment]
コメントありがとうございます。
修正しました。再度ご確認お願いします。
購入できなかった要因は、Herokuの環境設定が出来ていなかったためでした。
改めて環境設定を行い、動作確認をしました。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたので**LGTM**とさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
